version: "3"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password123
            POSTGRES_USER: user123
            POSTGRES_DB: db123
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    app:
        image: backend
        build: ./api
        ports:
            - 3000:3000
        depends_on:
            - db

    web:
        image: frontend
        build: ./web
        ports:
            - "5173:5173"
        restart: always
        depends_on:
            - app

    telegram:
        build: ./telegram
        environment:
            BOT_TOKEN: '7049351315:AAGCLVNWjiSb95k_z31yWkqxOCUfSHWpK28' # I have revoked this
        depends_on:
            - app
